# Use the official WordPress image as the base
FROM wordpress:latest

# Set the database credentials for WordPress
ENV WORDPRESS_DB_HOST db
ENV WORDPRESS_DB_USER wordpress
ENV WORDPRESS_DB_PASSWORD wordpress
ENV WORDPRESS_DB_NAME wordpress

# Expose the WordPress default port
EXPOSE 3080:80

# Use a volume to persist WordPress data
VOLUME /var/www/html/wp-content

# Copy the custom configuration file to the container
COPY custom.ini /usr/local/etc/php/conf.d/custom.ini
